# Generated by Django 5.2.4 on 2025-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hosted_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
